// <auto-generated />
using AutoCheck.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoCheck.Api.Migrations
{
    [DbContext(typeof(AutoCheckDbContext))]
    partial class AutoCheckDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoCheck.Domain.ItemVistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("ItemVistorias");
                });

            modelBuilder.Entity("AutoCheck.Domain.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quilometragem")
                        .HasColumnType("float");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");

                    b.HasDiscriminator<string>("TipoVeiculo").HasValue("Veiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AutoCheck.Domain.Caminhao", b =>
                {
                    b.HasBaseType("AutoCheck.Domain.Veiculo");

                    b.Property<double>("CapacidadeCargaToneladas")
                        .HasColumnType("float");

                    b.Property<int>("QuantidadeEixos")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Caminhao");
                });

            modelBuilder.Entity("AutoCheck.Domain.Carro", b =>
                {
                    b.HasBaseType("AutoCheck.Domain.Veiculo");

                    b.Property<int>("QuantidadePortas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Carro");
                });

            modelBuilder.Entity("AutoCheck.Domain.Moto", b =>
                {
                    b.HasBaseType("AutoCheck.Domain.Veiculo");

                    b.Property<int>("Cilindradas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Moto");
                });

            modelBuilder.Entity("AutoCheck.Domain.ItemVistoria", b =>
                {
                    b.HasOne("AutoCheck.Domain.Veiculo", null)
                        .WithMany("VistoriaRealizada")
                        .HasForeignKey("VeiculoId");
                });

            modelBuilder.Entity("AutoCheck.Domain.Veiculo", b =>
                {
                    b.Navigation("VistoriaRealizada");
                });
#pragma warning restore 612, 618
        }
    }
}
